import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import chalk from 'chalk';

const PLUGIN_TEMPLATE_FILES: Record<string, string | ((name: string, tier: string) => string)> = {
  'package.json': (name: string, tier: string) => JSON.stringify({
    name: `@forge/${name}`,
    version: '0.1.0',
    type: 'module',
    description: `ForgeKit plugin: ${name}`,
    main: './dist/index.js',
    types: './dist/index.d.ts',
    exports: { '.': './dist/index.js' },
    scripts: {
      build: 'tsc --project tsconfig.json',
      test: 'vitest run',
    },
    dependencies: { '@forge/spec': 'workspace:*' },
    devDependencies: { '@types/node': '^20.0.0', vitest: '^1.4.0' },
  }, null, 2),

  'tsconfig.json': () => JSON.stringify({
    extends: '../../../tsconfig.base.json',
    compilerOptions: { outDir: './dist', rootDir: './src' },
    include: ['src/**/*'],
  }, null, 2),

  'plugin.yaml': (name: string, tier: string) => `# ForgeKit Plugin Manifest — auto-generated by forge new plugin
name: "@forge/${name}"
version: 0.1.0
tier: ${tier}
description: TODO — fill in plugin description
entry: ./dist/index.js
forgeVersion: '>=0.2.0'
dependencies: []
provides: []
events: []
routes: []
`,

  'src/index.ts': (name: string) => `import type { ForgePlugin, PluginContext, HealthStatus } from '@forge/spec';
import { ${toPascalCase(name)}PluginSpec } from './PluginSpec.js';

export class ${toPascalCase(name)}Plugin implements ForgePlugin {
  readonly name = '@forge/${name}';
  readonly version = '0.1.0';
  readonly description = 'TODO: fill in description';
  readonly dependencies: string[] = [];
  readonly provides: string[] = [];
  readonly events: string[] = [];
  readonly spec = ${toPascalCase(name)}PluginSpec;

  private startTime = 0;

  async init(_ctx: PluginContext): Promise<void> {
    // TODO: initialize plugin state from context
  }

  async start(): Promise<void> {
    this.startTime = Date.now();
  }

  async stop(): Promise<void> {}

  async healthCheck(): Promise<HealthStatus> {
    return {
      status: 'healthy',
      plugin: this.name,
      version: this.version,
      uptime: Math.floor((Date.now() - this.startTime) / 1000),
    };
  }
}

export default function createPlugin(): ForgePlugin {
  return new ${toPascalCase(name)}Plugin();
}
`,

  'src/PluginSpec.ts': (name: string, tier: string) => `import type { PluginSpec } from '@forge/spec';

export const ${toPascalCase(name)}PluginSpec: PluginSpec = {
  tier: '${tier}',
  api: [
    // TODO: document each API method this plugin exposes
    // {
    //   name: 'myMethod',
    //   description: '...',
    //   parameters: [{ name: 'arg', type: 'string', required: true, description: '...' }],
    //   returns: 'void',
    // },
  ],
  dataModels: [],
  events: [],
  dependencies: [],
  usageExamples: [
    {
      title: 'Basic usage',
      description: 'How to use this plugin.',
      code: '// TODO: add usage example',
    },
  ],
};
`,

  'src/index.test.ts': (name: string) => `import { describe, it, expect } from 'vitest';
import { ${toPascalCase(name)}Plugin } from './index.js';

describe('${toPascalCase(name)}Plugin', () => {
  it('should have correct name and version', () => {
    const plugin = new ${toPascalCase(name)}Plugin();
    expect(plugin.name).toBe('@forge/${name}');
    expect(plugin.version).toBe('0.1.0');
  });

  it('should start and stop without errors', async () => {
    const plugin = new ${toPascalCase(name)}Plugin();
    await plugin.start();
    expect(() => plugin.stop()).not.toThrow();
  });

  it('should report healthy', async () => {
    const plugin = new ${toPascalCase(name)}Plugin();
    await plugin.start();
    const health = await plugin.healthCheck();
    expect(health.status).toBe('healthy');
    expect(health.plugin).toBe('@forge/${name}');
  });
});
`,
};

function toPascalCase(kebab: string): string {
  return kebab
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

export async function newPlugin(name: string, options: { description?: string; tier?: string }) {
  const pluginDir = resolve(process.cwd(), 'packages', name);

  if (existsSync(pluginDir)) {
    console.error(chalk.red(`Error: packages/${name} already exists.`));
    process.exit(1);
  }

  mkdirSync(pluginDir, { recursive: true });
  mkdirSync(resolve(pluginDir, 'src'), { recursive: true });

  for (const [filePath, contentFn] of Object.entries(PLUGIN_TEMPLATE_FILES)) {
    const content = typeof contentFn === 'function'
      ? contentFn(name, options.tier ?? 'extension')
      : contentFn;
    const fullPath = resolve(pluginDir, filePath);
    writeFileSync(fullPath, content);
    console.log(chalk.green(`  created: ${filePath}`));
  }

  console.log(chalk.bold(`\nPlugin @forge/${name} scaffolded at packages/${name}/`));
  console.log(`  Next: cd packages/${name} && pnpm install && pnpm build`);
}
