export interface APIDefinition {
  name: string;
  description: string;
  parameters?: ParameterSpec[];
  returns: string;
  example?: string;
}

export interface ParameterSpec {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface DataModel {
  name: string;
  description: string;
  fields: ModelField[];
}

export interface ModelField {
  name: string;
  type: string;
  description: string;
}

export interface EventDefinition {
  name: string;
  description: string;
  payloadType: string;
}

export interface DependencyDefinition {
  plugin: string;
  type: 'required' | 'optional';
  integration: string;       // how to use this dependency
  example: string;
}

export interface UsageExample {
  title: string;
  description: string;
  code: string;
}

export interface PluginSpec {
  api: APIDefinition[];
  dataModels: DataModel[];
  events: EventDefinition[];
  dependencies: DependencyDefinition[];
  usageExamples: UsageExample[];
  tier: 'core' | 'extension' | 'community';
  autogenerated?: boolean;   // set true if auto-generated from code
}
