import { describe, it, expect } from 'vitest';
import { Project, SyntaxKind } from 'ts-morph';

describe('PluginSpecGenerator', () => {
  it('should parse a plugin class and extract public methods', () => {
    // Create a temporary plugin source for testing
    const testPluginSrc = `
import type { ForgePlugin, PluginContext } from '@forge/spec';

export class TestPlugin implements ForgePlugin {
  readonly name = 'test-plugin';
  readonly version = '0.1.0';
  readonly description = 'Test';
  readonly dependencies: string[] = [];
  readonly provides: string[] = [];
  readonly events: string[] = ['test:event'];
  readonly spec = {} as any;

  async init(_ctx: PluginContext): Promise<void> {}
  async start(): Promise<void> {}
  async stop(): Promise<void> {}
  async healthCheck() { return { status: 'healthy', plugin: this.name, version: this.version, uptime: 0 }; }

  // Public API method
  doSomething(arg1: string, arg2: number): boolean {
    return true;
  }

  anotherMethod(): void {}
}
`;

    const project = new Project();
    const sf = project.createSourceFile('test-plugin.ts', testPluginSrc);
    const cls = sf.getClasses()[0];
    const lifecycleMethods = ['init', 'start', 'stop', 'healthCheck'];
    const publicMethods = cls.getMethods().filter(m => {
      if (lifecycleMethods.includes(m.getName())) return false;
      const modifiers = m.getModifiers();
      if (modifiers?.some(mod => mod.getText() === 'private' || mod.getText() === 'protected')) return false;
      return true;
    });

    expect(publicMethods.length).toBe(2);
    expect(publicMethods[0].getName()).toBe('doSomething');
    expect(publicMethods[0].getParameters()[0].getName()).toBe('arg1');
    expect(publicMethods[0].getParameters()[1].getName()).toBe('arg2');
    expect(publicMethods[1].getName()).toBe('anotherMethod');
  });

  it('should extract events array from plugin class', () => {
    const src = `
export class EventPlugin {
  readonly events: string[] = ['user:created', 'user:deleted'];
}
`;
    const project = new Project();
    const sf = project.createSourceFile('event-plugin.ts', src);
    const cls = sf.getClasses()[0];
    const eventsProp = cls.getProperty('events');
    expect(eventsProp).toBeTruthy();
    const init = eventsProp!.getInitializer();
    expect(init?.getKind()).toBe(SyntaxKind.ArrayLiteralExpression);
  });

  it('should produce a valid PluginSpec-shaped output', () => {
    const outputSpec = {
      tier: 'extension',
      api: [
        { name: 'myMethod', description: 'TODO', parameters: [{ name: 'x', type: 'string', required: true }], returns: 'void' },
      ],
      dataModels: [],
      events: [],
      dependencies: [],
      usageExamples: [{ title: 'Test', description: '...', code: '// test' }],
      autogenerated: true,
      autogeneratedAt: new Date().toISOString(),
    };

    expect(outputSpec).toHaveProperty('tier');
    expect(outputSpec).toHaveProperty('api');
    expect(Array.isArray(outputSpec.api)).toBe(true);
    expect(outputSpec.api[0]).toHaveProperty('name');
    expect(outputSpec.api[0]).toHaveProperty('description');
    expect(outputSpec).toHaveProperty('autogenerated', true);
  });
});
