#!/usr/bin/env node
import { Project, SyntaxKind, type ClassDeclaration, type MethodDeclaration, type ParameterDeclaration } from 'ts-morph';
import { resolve } from 'path';
import { writeFileSync, existsSync } from 'fs';
import chalk from 'chalk';

interface APIDef {
  name: string;
  description: string;
  parameters: { name: string; type: string; required: boolean }[];
  returns: string;
}

function main() {
  const pluginDir = process.argv[2];
  if (!pluginDir) {
    console.error('Usage: node dist/index.js <plugin-dir>');
    process.exit(1);
  }

  const resolved = resolve(process.cwd(), pluginDir);
  const srcIndex = resolve(resolved, 'src/index.ts');

  if (!existsSync(srcIndex)) {
    console.error(chalk.red(`Error: ${srcIndex} not found`));
    process.exit(1);
  }

  const project = new Project();
  project.addSourceFilesAtPaths(resolve(resolved, 'src/**/*.ts'));
  const sourceFile = project.getSourceFile(srcIndex);
  if (!sourceFile) {
    console.error(chalk.red(`Error: could not parse ${srcIndex}`));
    process.exit(1);
  }

  // Find the plugin class (implements ForgePlugin)
  const pluginClass = sourceFile.getClasses().find(cls => {
    const heritage = cls.getHeritageClauses();
    return heritage.some(h =>
      h.getToken() === SyntaxKind.ImplementsKeyword &&
      h.getTypeNodes().some(t => t.getText().includes('ForgePlugin'))
    ) || cls.getProperties().some(p => p.getName() === 'spec');
  });

  if (!pluginClass) {
    console.error(chalk.red(`Error: could not find plugin class implementing ForgePlugin in ${srcIndex}`));
    process.exit(1);
  }

  const className = pluginClass.getName() ?? 'UnknownPlugin';
  const pluginName = pluginClass.getProperty('name')?.getInitializer()?.asKind(SyntaxKind.StringLiteral)?.getLiteralText() ?? className;

  // Extract public methods (excluding lifecycle methods)
  const lifecycleMethods = ['init', 'start', 'stop', 'healthCheck'];
  const methods = pluginClass.getMethods().filter(m => {
    if (lifecycleMethods.includes(m.getName())) return false;
    // ts-morph v22: use getModifiers() check instead of isPrivate/isProtected
    const modifiers = m.getModifiers();
    if (modifiers?.some(mod => mod.getText() === 'private' || mod.getText() === 'protected')) return false;
    return true;
  });

  const apis: APIDef[] = methods.map(method => {
    const name = method.getName();
    const params = method.getParameters().map((p: ParameterDeclaration) => ({
      name: p.getName(),
      type: p.getType().getText(),
      required: !p.isOptional(),
    }));
    const returnType = method.getReturnType().getText();

    return {
      name,
      description: `TODO: describe ${name} method`,
      parameters: params,
      returns: returnType,
    };
  });

  // Build PluginSpec object
  const spec = {
    tier: 'extension',
    api: apis,
    dataModels: [],
    events: extractEvents(pluginClass),
    dependencies: [],
    usageExamples: [
      {
        title: 'Basic usage',
        description: 'TODO: add a concrete usage example',
        code: `// TODO: implement`,
      },
    ],
    autogenerated: true,
    autogeneratedAt: new Date().toISOString(),
  };

  const output = `// AUTO-GENERATED by @forge/spec-generator on ${new Date().toISOString()}
// Manual review REQUIRED — fill in descriptions and usageExamples
import type { PluginSpec } from '@forge/spec';

export const ${className}GeneratedSpec: PluginSpec = ${JSON.stringify(spec, null, 2)};
`;

  const outPath = resolve(resolved, '.forge-generated/PluginSpec.generated.ts');
  writeFileSync(outPath, output);

  console.log(chalk.green(`\n  Generated: .forge-generated/PluginSpec.generated.ts`));
  console.log(`  Class: ${className}`);
  console.log(`  Public methods found: ${methods.length}`);
  console.log(`  File: ${outPath}`);
  console.log(`\n  Next steps:`);
  console.log(`    1. Review .forge-generated/PluginSpec.generated.ts`);
  console.log(`    2. Merge relevant fields into src/PluginSpec.ts`);
  console.log(`    3. Fill in descriptions, dataModels, and usageExamples`);
}

function extractEvents(cls: ClassDeclaration) {
  const eventsProp = cls.getProperty('events');
  if (!eventsProp) return [];
  const init = eventsProp.getInitializer();
  if (!init || init.getKind() !== SyntaxKind.ArrayLiteralExpression) return [];
  return init.asKindOrThrow(SyntaxKind.ArrayLiteralExpression)
    .getElements()
    .map(el => {
      if (el.getKind() === SyntaxKind.StringLiteral) {
        return { name: (el as any).getLiteralText() ?? el.getText(), description: 'TODO', payloadType: 'unknown' };
      }
      return null;
    })
    .filter(Boolean);
}

main();
